[tool.isort]
multi_line_output=10
indent="  "
combine_as_imports=true

[tool.ruff]
target-version = "py39"
select = ["E", "F"]
ignore = ["E501", "E402"]

# Allow autofix for all enabled rules (when `--fix`) is provided.
fixable = ["A", "B", "C", "D", "E", "F"]
unfixable = []

# Exclude a variety of commonly ignored directories.
exclude = [
  ".git",
  ".mypy_cache",
  ".ruff_cache",
]

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.yapf]
based_on_style = "pep8"
column_limit = 100
indent_width = 2
continuation_indent_width = 2
continuation_align_style = "valign-right"
i18n_function_call = ["_", "N_"]
indent_dictionary_value = true
split_before_closing_bracket = false
spaces_around_default_or_named_assign = true
dedent_closing_brackets = true
blank_line_before_nested_class_or_def = false

[tool.pylint.MESSAGES_CONTROL]
disable= "C,I,R,bad-indentation"

